sudo: required
dist: trusty
language: node_js
node_js:
- '11'
matrix:
  fast_finish: true
install:
- npm install -g brunch
- npm install
script:
- npm run-script build
before_install:
- openssl aes-256-cbc -K $encrypted_c58dbf093b18_key -iv $encrypted_c58dbf093b18_iv
  -in deploy.pem.enc -out deploy.pem -d
